# Generated by Django 2.0.5 on 2018-05-29 17:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprof', '0001_initial'),
        ('garbage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('read', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('accept', models.BooleanField(default=False)),
                ('withdraw', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('negotiate_price', models.FloatField(default=0)),
                ('garbage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garbage', to='garbage.Garbage')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdminUser_inquiry', to='userprof.AdminUser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExtendedUser_inquiry', to='userprof.ExtendedUser')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('res_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('negotiate_price', models.FloatField(default=0)),
                ('continueMessage', models.BooleanField(default=True)),
                ('decline', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('garbage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.Garbage')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='message.Inquiry')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExtendedUser_offer', to='userprof.ExtendedUser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdminUser_offer', to='userprof.AdminUser')),
            ],
        ),
    ]
