# Generated by Django 2.0.4 on 2018-05-02 01:21

from django.db import migrations, models
import django.db.models.deletion
import garbage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprof', '0002_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(max_length=256)),
                ('cost', models.IntegerField(blank=True, default=5, null=True)),
                ('photos', models.ImageField(default='/default.png', upload_to=garbage.models.get_image_path)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('condition', models.IntegerField(blank=True, default=5, null=True)),
                ('postdate', models.DateField()),
                ('soldDate', models.DateField()),
                ('sold', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='userprof.ExtendedUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='userprof.AdminUser')),
                ('watched', models.ManyToManyField(to='userprof.ExtendedUser')),
            ],
        ),
    ]
