# Generated by Django 2.0.5 on 2018-05-29 17:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import garbage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprof', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(max_length=256)),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
                ('photos', models.ImageField(default='/media/default.png', upload_to=garbage.models.get_image_path)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('condition', models.IntegerField(blank=True, default=5, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('postdate', models.DateField(auto_now_add=True)),
                ('soldDate', models.DateField(blank=True, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='userprof.ExtendedUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='userprof.AdminUser')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_watch', models.DateField()),
                ('garbage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.Garbage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprof.ExtendedUser')),
            ],
        ),
        migrations.AddField(
            model_name='garbage',
            name='watched',
            field=models.ManyToManyField(blank=True, null=True, through='garbage.Watch', to='userprof.ExtendedUser'),
        ),
    ]
