# Generated by Django 2.0.4 on 2018-05-02 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbage',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='userprof.ExtendedUser'),
        ),
        migrations.AlterField(
            model_name='garbage',
            name='postdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='garbage',
            name='soldDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='garbage',
            name='watched',
            field=models.ManyToManyField(blank=True, null=True, to='userprof.ExtendedUser'),
        ),
    ]
