# Generated by Django 2.0.4 on 2018-05-02 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0002_auto_20180502_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbage',
            name='postdate',
            field=models.DateField(default=datetime.date),
        ),
    ]
